name: AdvancedOreGenerator
version: 1.2.8
author: Thatsmusic99
main: io.github.thatsmusic99.og.OreGenerator
api-version: 1.13
commands:
    aog:
        description: Main AOG command.
        default: false
        permission: aog.command
